name: "OpenTofu"
description: "Deploy OpenTofu"
outputs:
  app_url:
    value: ${{ steps.capture_output.outputs.app_url }}
runs:
  using: "composite"
  steps:

    - name: OpenTofu Init
      working-directory: ./infrastructure
      run: tofu init -backend-config="bucket=${{ env.PROJECT_ID }}-tf-state"
      shell: bash

    - name: OpenTofu Format, Validate and Plan
      working-directory: ./infrastructure
      run: |
        tofu fmt -check
        tofu validate
        tofu plan -input=false
      shell: bash

    - name: OpenTofu Apply
      working-directory: ./infrastructure
      if: github.ref == 'refs/heads/main'
      run: tofu apply -auto-approve -input=false
      shell: bash

    - name: Capture outputs
      working-directory: ./infrastructure
      id: capture_output
      run: |
        echo "app_url=$(terraform output -raw url)" >> $GITHUB_OUTPUT
      shell: bash
