services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    environment:
      - UIORIGIN=http://localhost:8000
      - DATABASE_HOST=database
    networks:
      - instaphant
    ports:
      - 8080:8080
    develop:
      watch:
        - path: ../api/
          action: rebuild

  ui:
    build:
      context: ../ui
      dockerfile: Dockerfile
    networks:
      - instaphant
    ports:
      - 8000:80
    develop:
      watch:
        - path: ../ui/
          action: rebuild
          ignore:
            - "../ui/node_modules"

  database:
    image: cassandra
    networks:
      - instaphant
    ports:
      - "9042:9042"
    volumes:
      - ../cassandra/cassandra-env.sh:/etc/cassandra/cassandra-env.sh
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'SELECT * FROM system_schema.keyspaces;'"]
      interval: 15s
      timeout: 10s
      retries: 5

  migrator:
    build:
      dockerfile: Dockerfile
      context: ../database
    environment:
      - CQLSH_HOST=database
      - CQLSH_PORT=9042
      - CQLVERSION=3.4.6
    networks:
      - instaphant
    depends_on:
      database:
        condition: service_healthy
    develop:
      watch:
        - path: ../database/
          action: rebuild

networks:
  instaphant: