services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    environment:
      - UIORIGIN=http://localhost:8000
    ports:
      - 8080:8080
    develop:
      watch:
        - path: ../api/
          action: rebuild

  ui:
    build:
      context: ../ui
      dockerfile: Dockerfile
    ports:
      - 8000:80
    develop:
      watch:
        - path: ../ui/
          action: rebuild
          ignore:
            - "../ui/node_modules"
