version: "3.8"

services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  ui:
    build:
      context: ../ui
      dockerfile: Dockerfile
    ports:
      - 8000:80