// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID     string `json:"id"`
	Author *User  `json:"author"`
	Text   string `json:"text"`
}

type Mutation struct {
}

type Post struct {
	ID          string     `json:"id"`
	Author      *User      `json:"author"`
	Description string     `json:"description"`
	Image       string     `json:"image"`
	Comments    []*Comment `json:"comments"`
}

type PostInput struct {
	Author      *string `json:"author,omitempty"`
	Description *string `json:"description,omitempty"`
	Image       *string `json:"image,omitempty"`
}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
